"""add assessment workflow flags

Revision ID: 0c5b50b2b07a
Revises: 83db4d57f31e
Create Date: 2026-07-18 00:46:09.167315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c5b50b2b07a'
down_revision = '83db4d57f31e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('questionnaire_completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('document_completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_column('document_completed')
        batch_op.drop_column('questionnaire_completed')

    # ### end Alembic commands ###
