"""Simplify assessment and document models

Revision ID: 10f836415164
Revises: 1aedd59a7216
Create Date: 2026-06-30 02:17:04.472843

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '10f836415164'
down_revision = '1aedd59a7216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_column('assessment_name')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('documents_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('assessment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assessment_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('documents_ibfk_2'), 'assessments', ['assessment_id'], ['id'])

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assessment_name', mysql.VARCHAR(length=200), nullable=False))

    # ### end Alembic commands ###
