"""Replace institute with university_id in users

Revision ID: 1aedd59a7216
Revises: 3f7c59a00c0d
Create Date: 2026-06-29 23:43:26.735493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1aedd59a7216'
down_revision = '3f7c59a00c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('university_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'university', ['university_id'], ['id'])
        batch_op.drop_column('institute')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institute', mysql.VARCHAR(length=120), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('university_id')

    # ### end Alembic commands ###
