"""Create ActivityLog table

Revision ID: 3e245ad885b3
Revises: 0c5b50b2b07a
Create Date: 2026-07-26 16:44:41.737138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e245ad885b3'
down_revision = '0c5b50b2b07a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('user_email', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_name', sa.String(length=150), nullable=False),
    sa.Column('resource', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('device', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_logs_event_id'), ['event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_activity_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_user_email'), ['user_email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_user_email'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_ip_address'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_event_type'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_event_id'))

    op.drop_table('activity_logs')
    # ### end Alembic commands ###
