"""Remove document_type from documents

Revision ID: 3f7c59a00c0d
Revises: 4e78de494b2f
Create Date: 2026-06-25 18:09:10.439575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f7c59a00c0d'
down_revision = '4e78de494b2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('document_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_type', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
