"""Merge detection engine alert schema

Revision ID: 410291bc15e8
Revises: ed604672e984
Create Date: 2026-08-05 08:09:23.857462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '410291bc15e8'
down_revision = 'ed604672e984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rule_name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('user_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('user_email', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('source_event_id', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('triggered_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('alert_metadata', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('activity_log_id', sa.Integer(), nullable=False))
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('assigned_role',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_alerts_event_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_severity'))
        batch_op.create_index(batch_op.f('ix_alerts_source_event_id'), ['source_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_triggered_at'), ['triggered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_user_email'), ['user_email'], unique=False)
        batch_op.create_foreign_key(None, 'activity_logs', ['activity_log_id'], ['id'])
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_alerts_user_email'))
        batch_op.drop_index(batch_op.f('ix_alerts_triggered_at'))
        batch_op.drop_index(batch_op.f('ix_alerts_source_event_id'))
        batch_op.create_index(batch_op.f('ix_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_event_id'), ['event_id'], unique=False)
        batch_op.alter_column('assigned_role',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('activity_log_id')
        batch_op.drop_column('alert_metadata')
        batch_op.drop_column('triggered_at')
        batch_op.drop_column('source_event_id')
        batch_op.drop_column('user_email')
        batch_op.drop_column('user_name')
        batch_op.drop_column('category')
        batch_op.drop_column('rule_name')

    # ### end Alembic commands ###
