"""remove version from documents

Revision ID: 47097721f5a7
Revises: 
Create Date: 2026-06-19 06:04:38.718548

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47097721f5a7'
down_revision = "70e9b27bd92a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=20), nullable=False))
        batch_op.alter_column('document_type',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('version')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.alter_column('document_type',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('source')

    # ### end Alembic commands ###
