"""Add actor identity to activity logs

Revision ID: 4b4bb35344f9
Revises: 83865457f3aa
Create Date: 2026-08-16 18:23:37.151510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b4bb35344f9'
down_revision = '83865457f3aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actor_type', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('actor_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_column('actor_id')
        batch_op.drop_column('actor_type')

    # ### end Alembic commands ###
