"""Add assessment_id to documents

Revision ID: 4e78de494b2f
Revises: 47097721f5a7
Create Date: 2026-06-25 16:49:19.108151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e78de494b2f'
down_revision = '47097721f5a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assessment_name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('risk_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('compliance_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assessment_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('extracted_text', sa.Text(), nullable=False))
        batch_op.create_foreign_key(None, 'assessments', ['assessment_id'], ['id'])

    with op.batch_alter_table('university', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_domain', sa.String(length=100), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('otp', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('otp_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('otp_expiry')
        batch_op.drop_column('otp')
        batch_op.drop_column('is_verified')

    with op.batch_alter_table('university', schema=None) as batch_op:
        batch_op.drop_column('email_domain')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('extracted_text')
        batch_op.drop_column('assessment_id')

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('compliance_score')
        batch_op.drop_column('risk_level')
        batch_op.drop_column('assessment_name')

    # ### end Alembic commands ###
