"""test

Revision ID: 4eaf82462a8c
Revises: 3c9ec25b9e6e
Create Date: 2026-07-07 18:02:51.360673

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4eaf82462a8c'
down_revision = '3c9ec25b9e6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_control_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('control_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('evidence_source', sa.String(length=50), nullable=False),
    sa.Column('affected_frameworks', sa.Text(), nullable=False),
    sa.Column('implemented_requirements', sa.Text(), nullable=True),
    sa.Column('missing_requirements', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment_documents',
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('assessment_id', 'document_id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('university_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('original_filename', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('stored_filename', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('extracted_text', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('source', sa.String(length=20), nullable=False))
        batch_op.drop_constraint(batch_op.f('documents_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'university', ['university_id'], ['id'])
        batch_op.drop_column('file_name')
        batch_op.drop_column('assessment_id')
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', mysql.VARCHAR(length=500), nullable=False))
        batch_op.add_column(sa.Column('assessment_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('file_name', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('documents_ibfk_1'), 'assessments', ['assessment_id'], ['id'])
        batch_op.drop_column('source')
        batch_op.drop_column('extracted_text')
        batch_op.drop_column('stored_filename')
        batch_op.drop_column('original_filename')
        batch_op.drop_column('university_id')

    op.drop_table('assessment_documents')
    op.drop_table('assessment_control_results')
    # ### end Alembic commands ###
