"""Add assessment mode

Revision ID: 7a1866addc9c
Revises: f0b1c78178e7
Create Date: 2026-07-04 18:21:15.975857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a1866addc9c'
down_revision = 'f0b1c78178e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assessment_mode', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_column('assessment_mode')

    # ### end Alembic commands ###
