"""Add university to activity logs

Revision ID: 83865457f3aa
Revises: 410291bc15e8
Create Date: 2026-08-16 00:06:39.618397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83865457f3aa'
down_revision = '410291bc15e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('university_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_activity_logs_university_id'), ['university_id'], unique=False)
        batch_op.create_foreign_key(None, 'university', ['university_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_activity_logs_university_id'))
        batch_op.drop_column('university_id')

    # ### end Alembic commands ###
