"""Add confidence and evidence to compliance results

Revision ID: 83db4d57f31e
Revises: 318308c27bb0
Create Date: 2026-07-17 18:32:01.867024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83db4d57f31e'
down_revision = 'd8260ea66d11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compliance_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('evidence', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compliance_results', schema=None) as batch_op:
        batch_op.drop_column('evidence')
        batch_op.drop_column('confidence')

    # ### end Alembic commands ###
