"""sync models

Revision ID: d2b2890dafeb
Revises: acdc99ce7441
Create Date: 2026-06-21 19:59:41.662488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2b2890dafeb'
down_revision = 'acdc99ce7441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assessment_name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('risk_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('compliance_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('university', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_domain', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('university', schema=None) as batch_op:
        batch_op.drop_column('email_domain')

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('compliance_score')
        batch_op.drop_column('risk_level')
        batch_op.drop_column('assessment_name')

    op.drop_table('documents')
    # ### end Alembic commands ###
