"""Add recommendations table

Revision ID: d8260ea66d11
Revises: 318308c27bb0
Create Date: 2026-07-16 19:32:28.990429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8260ea66d11'
down_revision = '318308c27bb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.String(length=4), nullable=False),
    sa.Column('control_name', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('estimated_effort', sa.String(length=50), nullable=False),
    sa.Column('implementation_timeline', sa.String(length=100), nullable=False),
    sa.Column('implementation_cost', sa.String(length=100), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('technical_steps', sa.JSON(), nullable=False),
    sa.Column('policy_steps', sa.JSON(), nullable=False),
    sa.Column('business_impact', sa.Text(), nullable=False),
    sa.Column('success_metrics', sa.JSON(), nullable=False),
    sa.Column('reference', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_assessment_id'), ['assessment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_assessment_id'))

    op.drop_table('recommendations')
    # ### end Alembic commands ###
