"""add monitoring control analysis

Revision ID: df61a1911864
Revises: e851c2e6122a
Create Date: 2026-08-19 19:44:29.245106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df61a1911864'
down_revision = 'e851c2e6122a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring_control_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.String(length=4), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('effectiveness', sa.String(length=50), nullable=False),
    sa.Column('updated_risk', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monitoring_control_analysis')
    # ### end Alembic commands ###
