"""Add university to alerts

Revision ID: e851c2e6122a
Revises: 4b4bb35344f9
Create Date: 2026-08-16 18:54:49.219293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e851c2e6122a'
down_revision = '4b4bb35344f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('university_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_alerts_university_id'), ['university_id'], unique=False)
        batch_op.create_foreign_key(None, 'university', ['university_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_alerts_university_id'))
        batch_op.drop_column('university_id')

    # ### end Alembic commands ###
