"""add threat analysis model

Revision ID: ed604672e984
Revises: 20007133191c
Create Date: 2026-08-04 00:12:22.386305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed604672e984'
down_revision = '20007133191c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('likely_attack_type', sa.String(length=100), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('impact', sa.Text(), nullable=False),
    sa.Column('recommended_actions', sa.JSON(), nullable=False),
    sa.Column('investigation_steps', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('analysis_version', sa.String(length=20), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('threat_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_threat_analyses_alert_id'), ['alert_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_threat_analyses_risk_level'), ['risk_level'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threat_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threat_analyses_risk_level'))
        batch_op.drop_index(batch_op.f('ix_threat_analyses_alert_id'))

    op.drop_table('threat_analyses')
    # ### end Alembic commands ###
