"""Change assessment answer from boolean to string

Revision ID: f0b1c78178e7
Revises: 10f836415164
Create Date: 2026-06-30 15:29:45.357136

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0b1c78178e7'
down_revision = '10f836415164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_answers', schema=None) as batch_op:
        batch_op.alter_column('answer',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_answers', schema=None) as batch_op:
        batch_op.alter_column('answer',
               existing_type=sa.String(length=30),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)

    # ### end Alembic commands ###
